import React from "react";

export default function PrivacyPolicyEn() {
  return (
    <div className="legal-page">
      <a href="#/" className="btn-home">Home</a>
      <h1>Privacy Policy</h1>

      <section>
        <h2>1. Overview</h2>
        <p>
          The following information provides a simple overview of what happens to your personal data when you visit this website.
          Personal data means any data by which you could be personally identified.
        </p>
      </section>

      <section>
        <h2>2. Data Collection</h2>
        <p>
          <strong>Who is responsible for data collection on this website?</strong><br />
          Data processing on this website is carried out by the website operator. The operator's contact details can be found in the
          imprint of this website.
        </p>
        <p>
          <strong>How do we collect your data?</strong><br />
          Some data is collected when you provide it to us. For example, this could be data that you enter in a contact form.
        </p>
        <p>
          Other data is collected automatically by our IT systems when you visit the website. This data is primarily technical data
          such as the browser and operating system you are using or the time the page was accessed.
        </p>
      </section>

      <section>
        <h2>3. Hosting</h2>
        <p>
          This website is hosted on privately operated infrastructure in Germany. The personal data collected on this website is
          stored on the host's systems.
        </p>
      </section>

      <section>
        <h2>4. General Notes</h2>
        <h3>Data Protection</h3>
        <p>
          We take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance
          with the statutory data protection regulations as well as this privacy policy.
        </p>
        <h3>SSL or TLS Encryption</h3>
        <p>
          This site uses SSL or TLS encryption for security reasons and to protect the transmission of confidential content. You can
          recognize an encrypted connection when the browser address line changes from "http://" to "https://".
        </p>
      </section>

      <section>
        <h2>5. Data Collection on this Website</h2>
        <h3>Cookies</h3>
        <p>
          This website does not use tracking cookies. We only use local storage to keep your timer preferences between sessions.
          This data stays on your device and is never transmitted to our servers.
        </p>
        <h3>Server Log Files</h3>
        <p>
          The provider of the pages automatically collects and stores information in server log files that your browser automatically
          transmits to us. These are:
        </p>
        <ul>
          <li>Browser type and version</li>
          <li>Operating system used</li>
          <li>Referrer URL</li>
          <li>Hostname of the accessing computer</li>
          <li>Time of the server request</li>
          <li>IP address</li>
        </ul>
        <p>
          This data will not be combined with data from other sources.
        </p>
      </section>

      <section>
        <h2>6. Advertising & Analytics</h2>
        <h3>Google AdSense</h3>
        <p>
          This website uses Google AdSense, a service for including advertisements by Google Ireland Limited ("Google"), Gordon House,
          Barrow Street, Dublin 4, Ireland.
        </p>
        <p>
          Google AdSense uses cookies and web beacons (invisible graphics). These technologies can evaluate information such as visitor
          traffic on these pages.
        </p>
        <p>
          The information generated by cookies and web beacons about your use of this website (including your IP address) and delivery
          of advertising formats is transmitted to a Google server and stored there.
        </p>
        <p>
          Google AdSense is used on the basis of Art. 6 para. 1 lit. f GDPR. The website operator has a legitimate interest in analyzing
          user behaviour to optimize both their website and their advertising.
        </p>
        <p>
          For more information about Google AdSense, see
          <a href="https://policies.google.com/technologies/ads" target="_blank" rel="noopener noreferrer">
            https://policies.google.com/technologies/ads
          </a>.
        </p>
      </section>

      <section>
        <h2>7. Your Rights</h2>
        <p>You have the following rights:</p>
        <ul>
          <li>Right to obtain information about your stored data</li>
          <li>Right to rectification of incorrect data</li>
          <li>Right to deletion of your data</li>
          <li>Right to restriction of processing</li>
          <li>Right to data portability</li>
          <li>Right to object to processing</li>
          <li>Right to lodge a complaint with a supervisory authority</li>
        </ul>
      </section>

      <p className="legal-lang-switch">
        Need the German text? <a href="#/datenschutz">Zur Datenschutzerklärung</a>
      </p>
    </div>
  );
}
